-libraryjars C:\Program Files\Sun\SonyEricsson\JavaME_SDK_CLDC\WTK2\lib\wma20.jar;C:\Program Files\Sun\SonyEricsson\JavaME_SDK_CLDC\WTK2\lib\jsr179.jar;C:\Program Files\Sun\SonyEricsson\JavaME_SDK_CLDC\WTK2\lib\midpapi20.jar;C:\Program Files\Sun\SonyEricsson\JavaME_SDK_CLDC\WTK2\lib\cldcapi11.jar
-injars C:\Program Files\Sun\SonyEricsson\JavaME_SDK_CLDC\WTK2\apps\MobileSPBTransport\bin\MobileSPBTransport.jar
-outjar C:\DOCUME~1\6EED~1\LOCALS~1\Temp\MobileSPBTransport.jar
-keep public class * extends javax.microedition.midlet.MIDlet 
-dontusemixedcaseclassnames
